---
- name: Install RUST in ubuntu
  hosts: test_app
  vars:
    go_shar_key: "2255eb3e4e824dd7d5fcdc2e7f84534371c186312e546fb1086a34c17752f431"
    go_download_link: "https://golang.org/dl/go1.17.2.linux-amd64.tar.gz"

  tasks:
    - name: Install GoLang
      block:

        - name : create go dir
          file:
            path: "/usr/filius/"
            group: vagrant
            mode: 700
            state: directory
        
        - name: Expand tar file
          unarchive:
            src: "{{ go_download_link }}"
            validate_certs: yes
            dest: "/usr/filius/"
            remote_src: True
            creates: " /usr/filius/go"
        
        - name: Adding to Path
          become: true
          shell: echo "export PATH=$PATH:/usr/filius/go/bin" >> /etc/profile

      